parameters:
#    hermes_model.example.class: Hermes\ModelBundle\Example

services:
#    hermes_model.example:
#        class: %hermes_model.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
