hermes_model:
    resource: "@HermesModelBundle/Resources/config/routing.yml"
    prefix:   /

hermes_report:
    resource: "@HermesAdminBundle/Resources/config/routing.yml"
    prefix:   /

login:
    path:   /login
    defaults:  { _controller: HermesAdminBundle:Employee:login }
login_check:
    path:   /login_check