security:
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity:
                class: Hermes\ModelBundle\Entity\Employee
                property: email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            anonymous:  ~

        secured_area:
            pattern:    ^/
            form_login: ~

            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"
    encoders:
        Hermes\ModelBundle\Entity\Employee:
              algorithm: bcrypt
              cost:      15

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
