hermes_admin_homepage:
    pattern:  /
    defaults: { _controller: HermesAdminBundle:Default:index }

hermes_report_homepage:
    pattern: /branches
    defaults: { _controller: HermesAdminBundle:Report:index }

hermes_report_branches_amount_of_sales:
    pattern: /branches/amount-of-sales
    defaults: { _controller: HermesAdminBundle:Report:branchesByAmountOfSales}

hermes_report_branches_price_ranges:
    pattern: /branches/price-ranges
    defaults: { _controller: HermesAdminBundle:Report:branchesByPriceRanges}

hermes_report_countries_most_popular:
    pattern: /countries/most-popular
    defaults: { _controller: HermesAdminBundle:Report:mostPopularCountries}

